spring.application.name=File_Uploading_demo
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=2KB
spring.file-upload-path=src/main/resources/files